//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zDrive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zDrive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zDrive - Информация о информационных хранилищах.
        /// </summary>
        public static string AppTitle_Text {
            get {
                return ResourceManager.GetString("AppTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозапуск.
        /// </summary>
        public static string AutorunCheckbox_Text {
            get {
                return ResourceManager.GetString("AutorunCheckbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть приложение.
        /// </summary>
        public static string CloseButton_Text {
            get {
                return ResourceManager.GetString("CloseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть недоступные.
        /// </summary>
        public static string HideUnavailableCheckbox_Text {
            get {
                return ResourceManager.GetString("HideUnavailableCheckbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2:F2}{3} Свободно.
        /// </summary>
        public static string InfoFormat_Free {
            get {
                return ResourceManager.GetString("InfoFormat_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2:F2}{3}/{0:F2}{1}.
        /// </summary>
        public static string InfoFormat_FreeMax {
            get {
                return ResourceManager.GetString("InfoFormat_FreeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4:F2}{5}/{0:F2}{1}.
        /// </summary>
        public static string InfoFormat_UsedMax {
            get {
                return ResourceManager.GetString("InfoFormat_UsedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to байт.
        /// </summary>
        public static string Size_bytes {
            get {
                return ResourceManager.GetString("Size_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Б.
        /// </summary>
        public static string Size_bytes_Short {
            get {
                return ResourceManager.GetString("Size_bytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступен.
        /// </summary>
        public static string Size_bytes_Unvailable {
            get {
                return ResourceManager.GetString("Size_bytes_Unvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недост..
        /// </summary>
        public static string Size_bytes_Unvailable_Short {
            get {
                return ResourceManager.GetString("Size_bytes_Unvailable_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГБ.
        /// </summary>
        public static string Size_Gigabytes_Short {
            get {
                return ResourceManager.GetString("Size_Gigabytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гигабайт.
        /// </summary>
        public static string Size_Gigagabytes {
            get {
                return ResourceManager.GetString("Size_Gigagabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to килобайт.
        /// </summary>
        public static string Size_Kilobytes {
            get {
                return ResourceManager.GetString("Size_Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КБ.
        /// </summary>
        public static string Size_Kilobytes_Short {
            get {
                return ResourceManager.GetString("Size_Kilobytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мегабайт.
        /// </summary>
        public static string Size_Megabytes {
            get {
                return ResourceManager.GetString("Size_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МБ.
        /// </summary>
        public static string Size_Megabytes_Short {
            get {
                return ResourceManager.GetString("Size_Megabytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to петабайт.
        /// </summary>
        public static string Size_Petabytes {
            get {
                return ResourceManager.GetString("Size_Petabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПБ.
        /// </summary>
        public static string Size_Petabytes_Short {
            get {
                return ResourceManager.GetString("Size_Petabytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to терабайт.
        /// </summary>
        public static string Size_Terabytes {
            get {
                return ResourceManager.GetString("Size_Terabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТБ.
        /// </summary>
        public static string Size_Terabytes_Short {
            get {
                return ResourceManager.GetString("Size_Terabytes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверх всех окон.
        /// </summary>
        public static string TopmostCheckbox_Text {
            get {
                return ResourceManager.GetString("TopmostCheckbox_Text", resourceCulture);
            }
        }
    }
}
